### ISSUE TITLE
Cloudwatch: Create a Scheduled Event

### ISSUE THREAD

**Issue by rik2803** [rik2803/aws-cfn-gen#3]
Create a scheduled CloudWatch event and attach a target by importing
a value (ARN) from the exports of another CloudFormation stack.

For example:

```yaml
cw:
  scheduled_rules:
    - name: MyDaily6AMSchedule
      description: "Trigger daily at 6 AM"
      schedule_expression: "cron(0 6 * * ? *)"
      targets:
        - type: import
          value: MyCloudformationTemplate-MyLambdaFunction
```
